
const productData=[
  {
    id:1,
    name:"Hp Core i5 10th gen",
    price:333,
    description:"Description : Hp core i5..",
    category:"Laptop",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdZw_zf9-o9VSXDCA8khvp0Hx4qkZMFbtKwg&usqp=CAU",
  },
    {
    id:2,
    name:"Hp Core i3 11th gen",
    price:444,
    description:"Description : Hp core i3..",
    category:"Laptop",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXo32tsLc6sLuc5a5a6lGQLWxQToNn1f_VPA&usqp=CAU",
  },
   {
    id:3,
    name:"Lenovo Core i3 11th gen",
    price:474,
    description:"Description : Lenovo core i3..",
    category:"Laptop",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdeGJCjIwKytQzDUBnspc_PBLkmUgH6ioKHg&usqp=CAU",
  },
     {
    id:4,
    name:"Lenovo Core i5 10th gen",
    price:356,
    description:"Description : Lenovo core i5..",
    category:"Laptop",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6ej-VWQ_vogDbM0h8Dkl9Hw5W9NOrbj6eQg&usqp=CAU",
  },
     {
    id:5,
    name:"I phone 10",
    price:1200,
    description:"Description : Iphone 10...",
    category:"mobiles",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLe8AHDCAuHACoP66f_5imJe9CoxA1E2pUxg&usqp=CAU",
  },
     {
    id:6,
    name:"I phone 11",
    price:1600,
    description:"Description : Iphone 11...",
    category:"mobiles",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6RpFHLKFyOYkd0ZsaxObIHAtHXU4OCKu50w&usqp=CAU",
  },
     {
    id:7,
    name:"I phone 12",
    price:1800,
    description:"Description : Iphone 12...",
    category:"mobiles",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb-4iBANRINB45kOrX1KRGrF6Gq7Vu5SQ-iQ&usqp=CAU",
  },
      {
    id:8,
    name:"I phone 12 pro max",
    price:1990,
    description:"Description : Iphone 12 pro max...",
    category:"mobiles",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb-4iBANRINB45kOrX1KRGrF6Gq7Vu5SQ-iQ&usqp=CAU",
  },
   {
    id:8,
    name:"I phone 13",
    price:1900,
    description:"Description : Iphone 13....",
    category:"mobiles",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb-4iBANRINB45kOrX1KRGrF6Gq7Vu5SQ-iQ&usqp=CAU",
  },
   {
    id:9,
    name:"Lenovo Core i7 10th gen",
    price:1356,
    description:"Description : Lenovo core i7..",
    category:"Laptop",
    picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6ej-VWQ_vogDbM0h8Dkl9Hw5W9NOrbj6eQg&usqp=CAU",
  },
  ]

export default  productData